globals:
  comment: test_MNIST
  debug: false
  ex_name: 000_base_line_search
  num_epochs: 100
  seed: 42
  use_amp: false
model:
  name: EffNetV2_b0
  params:
    num_classes: 1
data:
  test_data_dir: input/petfinder-pawpularity-score/test
  test_df_path: input/petfinder-pawpularity-score/test.csv
  train_data_dir: input/petfinder-pawpularity-score/train
  train_df_path: input/petfinder-pawpularity-score/train.csv
dataset:
  name: MNIST_test
  params:
    aug: true
    img_size: 256
loader:
  test:
    batch_size: 1
    num_workers: 0
    shuffle: false
  train:
    batch_size: 8
    num_workers: 0
    shuffle: true
  valid:
    batch_size: 16
    num_workers: 0
    shuffle: false
split:
  name: StratifiedKFold
  params:
    n_splits: 4
    random_state: 42
    shuffle: true
loss:
  name: RMSELoss
  params: null
optimizer:
  name: Adam
  params:
    lr: 0.001
scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10
early_stopping:
  delta: 0
  patience: 6
hydra:
  run:
    dir: ./outputs/${globals.ex_name}/${now:%y%m%d}-${globals.comment}
  sweep:
    dir: ./data/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: try${hydra.job.num}
  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s] line%(lineno)d [%(levelname)s] %(message)s'
