globals:
  ex_name: test3
  debug: false
  num_epochs: 100
  seed: 42
  user: miyazaki
data:
  test_data_dir: ./input/petfinder-pawpularity-score/test
  test_df_path: ./input/petfinder-pawpularity-score/test.csv
  train_data_dir: ./input/petfinder-pawpularity-score/train
  train_df_path: ./input/petfinder-pawpularity-score/train.csv
defaults:
- model: EffNetV2_b0
- dataset: DefaultDataset
- loader: DefaultDataloader
- split: StratifiedKFold
- optimizer: Adam
- loss: BCEwithLogitsLoss
- scheduler: CosineAnnealingLR
- callback: DefaultCallback
hydra:
  run:
    dir: ./outputs/${globals.ex_name}
  sweep:
    dir: ./outputs/${globals.ex_name}
    subdir: ${defaults.model} - ${defaults.dataset}
  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s] line%(lineno)d [%(levelname)s] %(message)s'
